# Generated by Django 6.0.8 on 2026-08-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('archive_id', models.UUIDField(help_text='Stable identifier of the archived object. Immutable.', primary_key=True, serialize=False)),
                ('archived_model', models.CharField(help_text='Which archive table the copy is in, e.g. "objectdb".', max_length=32)),
                ('archived_pk', models.IntegerField(help_text='Primary key of the copy within the archive database.')),
                ('last_archived', models.DateTimeField(help_text='When the archived copy was last written.')),
                ('last_restored', models.DateTimeField(blank=True, help_text='When the object was last restored. Null if never.', null=True)),
            ],
            options={
                'verbose_name': 'archive record',
                'verbose_name_plural': 'archive records',
                'indexes': [models.Index(fields=['last_archived'], name='archive_last_archived_idx')],
            },
        ),
    ]
